services:
  - type: web
    name: agrispark-2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: BASE_URL
        sync: false
      - key: SECRET_TRIGGER_CODE
        value: agrispark123
